name: Sync to Hugging Face hub
on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: NiansuhAI
          SPACE_NAME: Bingo
        run: |
          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME huggingface
          cd huggingface
          git config user.name Niansuh
          git config user.email niansuhtech@gmail.com
          echo "Last deploy time: $(date)" > DEPLOY_INFO.txt
          git add DEPLOY_INFO.txt
          git commit -m "auto deploy $(date)"
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main -f
